WARNING  pytest_result_log:plugin.py:122 ------------Start: testcases/test_collect_news.py::test_collect_succ------------
WARNING  pytest_result_log:plugin.py:128 -------------End: testcases/test_collect_news.py::test_collect_succ-------------